### ISSUE TITLE
not a git repository error in proper git repo

### ISSUE THREAD

**Issue by leverglowh** [codeprintsdev/client#3]
I'm getting
```
fatal: not a git repository (or any of the parent directories): .git
Error: Cannot read project history

Caused by:
    command ["git", "log", "--date=short", "--pretty=format:%ad"] exited with code 128
```
in a local repository even though running `git log --date=short-local --pretty=format:%ad` works printing the date list.

Things I tried:
- [x] Both on windows and mac
- [x] Made sure `.git` exists in the directory
- [x] On Mac set the read+write permissions to `.git`
- [x] Same error on other repos, so it's not *the* local repo

I don't know anything about docker actually, my steps for installing and using it are:
Mac:
- cd into local repo
- `brew install docker`
- `brew install docker-machine`
- `brew install --cask virtualbox`
- `docker-machine create --driver virtualbox default`
- `docker-machine restart`
- `eval "$(docker-machine env default)"`
- ``docker run -v `pwd`/repo codeprints/client`` which downloads something and then prints the error.

Windows:
- Tried installing docker toolbox, which gave some error on hyper v so uninstalled it
- Installed docker daemon and got confused
- Finally installed docker desktop from https://www.docker.com/products/docker-desktop
- cd into local repo
- ``docker run -v `pwd`/repo codeprints/client`` which downloads something and then prints the error.

So what's wrong here?

**Comment by mre** [comment]
Wow, that was a thorough issue description. Thanks for reporting back and for taking the time for writing.
I'm sorry to tell you, but it's simply a typo in the `README.md`. 😅  It should have been

```
docker run -v `pwd`:/repo codeprints/client
```

Already fixed in the docs now.

**Comment by leverglowh** [comment]
> I'm sorry to tell you, but it's simply a typo in the `README.md`. 😅

And now I feel stupid. Thank you!

**Comment by mre** [comment]
> And now I feel stupid.

Story of my life. 😆

**Comment by mre** [comment]
BTW: the project is called codeprints-analyzer now.

So the new command is

```
docker run -v `pwd`:/repo codeprints/analyzer
```

We renamed the project to emphasize that it works completely offline (whereas "client" would indicate that it's communicating with a server somehow).
